[package]
name = "zstdp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
env_logger = "0.11.5"
flate2 = "1.0.35"
log = "0.4.22"
mime_guess = "2.0.5"
percent-encoding = "2.3.1"
zstd = "0.12"
